# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unab', '0002_auto_20170705_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='comuna',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
